import spacy.attrs
import spacy.cfile
import spacy.gold
import spacy.lexeme
import spacy.matcher
import spacy.morphology
import spacy.orth
import spacy.parts_of_speech
import spacy.pipeline
import spacy.serialize.bits
import spacy.serialize.huffman
import spacy.serialize.packer
import spacy.strings
import spacy.symbols
import spacy.syntax._parse_features
import spacy.syntax._state
import spacy.syntax.arc_eager
import spacy.syntax.beam_parser
import spacy.syntax.iterators
import spacy.syntax.ner
import spacy.syntax.nonproj
import spacy.syntax.parser
import spacy.syntax.stateclass
import spacy.syntax.transition_system
import spacy.tagger
import spacy.tokenizer
import spacy.tokens.doc
import spacy.tokens.span
import spacy.tokens.token
import spacy.vocab
